# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Driver.create!({ name: 'Nico Rosberg', price: 50000000, driverId: 'rosberg'  })
Driver.create!({ name: 'Lewis Hamilton', price: 43000000, driverId: 'hamilton'  })
Driver.create!({ name: 'Daniel Ricciardo', price: 29000000, driverId: 'ricciardo'  })
Driver.create!({ name: 'Sebastian Vettel', price: 54000000, driverId: 'vettel'  })
Driver.create!({ name: 'Valtteri Bottas', price: 22000000, driverId: 'bottas'  })
Driver.create!({ name: 'Felipe Massa', price: 27000000, driverId: 'massa'  })
Driver.create!({ name: 'Kimi Räikkönen', price: 53000000, driverId: 'raikkonen'  })
Driver.create!({ name: 'Fernando Alonso', price: 55000000, driverId: 'alonso'  })
Driver.create!({ name: 'Jenson Button', price: 45000000, driverId: 'button'  })
Driver.create!({ name: 'Kevin Magnussen', price: 30000000, driverId: 'kevin_magnussen' })
Driver.create!({ name: 'Nico Hülkenberg', price: 38000000, driverId: 'hulkenberg' })
Driver.create!({ name: 'Sergio Perez', price: 33000000, driverId: 'perez' })
Driver.create!({ name: 'Jean-Eric Vergne', price: 20000000, driverId: 'vergne' })
Driver.create!({ name: 'Daniil Kvyat', price: 15000000, driverId: 'kvyat' })
Driver.create!({ name: 'Romain Grosjean', price: 40000000, driverId: 'grosjean' })
Driver.create!({ name: 'Pastor Maldonado', price: 33000000, driverId: 'maldonado' })
Driver.create!({ name: 'Adrian Sutil', price: 30000000, driverId: 'sutil' })
Driver.create!({ name: 'Esteban Gutiérrez', price: 25000000, driverId: 'gutierrez' })
Driver.create!({ name: 'Jules Bianchi', price: 15000000, driverId: 'jules_bianchi' })
Driver.create!({ name: 'Max Chilton', price: 11000000, driverId: 'chilton' })
Driver.create!({ name: 'Kamui Kobayashi', price: 18000000, driverId: 'kobayashi' })
Driver.create!({ name: 'Marcus Ericsson', price: 10000000, driverId: 'ericsson' })


ChassisManufacturer.create!({ name: 'Mercedes Grand Prix', price: 55000000, constructorId: 'mercedes' })
ChassisManufacturer.create!({ name: 'Red Bull', price: 61750000, constructorId: 'red_bull' })
ChassisManufacturer.create!({ name: 'Williams', price: 25000000, constructorId: 'williams' })
ChassisManufacturer.create!({ name: 'Ferrari', price: 50000000, constructorId: 'ferrari' })
ChassisManufacturer.create!({ name: 'McLaren', price: 40000000, constructorId: 'mclaren' })
ChassisManufacturer.create!({ name: 'Force India F1', price: 30000000, constructorId: 'force_india' })
ChassisManufacturer.create!({ name: 'Scuderia Toro Rosso', price: 22000000, constructorId: 'toro_rosso' })
ChassisManufacturer.create!({ name: 'Lotus Renault', price: 35000000, constructorId: 'lotus_f1' })
ChassisManufacturer.create!({ name: 'Sauber', price: 30000000, constructorId: 'sauber' })
ChassisManufacturer.create!({ name: 'Marussia', price: 20000000, constructorId: 'marussia' })
ChassisManufacturer.create!({ name: 'Caterham', price: 20000000, constructorId: 'caterham' })


Engine.create!({ name: 'Mercedes Grand Prix', price: 55000000, constructorId: 'mercedes' })
Engine.create!({ name: 'Red Bull', price: 61750000, constructorId: 'red_bull' })
Engine.create!({ name: 'Williams', price: 25000000, constructorId: 'williams' })
Engine.create!({ name: 'Ferrari', price: 50000000, constructorId: 'ferrari' })
Engine.create!({ name: 'McLaren', price: 40000000, constructorId: 'mclaren' })
Engine.create!({ name: 'Force India F1', price: 30000000, constructorId: 'force_india' })
Engine.create!({ name: 'Scuderia Toro Rosso', price: 22000000, constructorId: 'toro_rosso' })
Engine.create!({ name: 'Lotus Renault', price: 35000000, constructorId: 'lotus_f1' })
Engine.create!({ name: 'Sauber', price: 30000000, constructorId: 'sauber'  })
Engine.create!({ name: 'Marussia', price: 20000000, constructorId: 'marussia' })
Engine.create!({ name: 'Caterham', price: 20000000, constructorId: 'caterham' })

User.create!({ name: 'Homer', email: 'homer@powerplant.nuke', password: 'a', password_confirmation: 'a'})
User.create!({ name: 'Marge', email: 'marge@home.net', password: 'a', password_confirmation: 'a'})
User.create!({ name: 'Lisa', email: 'lisa@home.net', password: 'a', password_confirmation: 'a'})

PlayerTeam.create!({ user_id: 1, driver1_id: 1, driver2_id: 3, engine_id: 1, chassis_manufacturer_id: 2 })
PlayerTeam.create!({ user_id: 1, driver1_id: 1, driver2_id: 3, engine_id: 5, chassis_manufacturer_id: 2 })
PlayerTeam.create!({ user_id: 1, driver1_id: 3, driver2_id: 1, engine_id: 5, chassis_manufacturer_id: 2 })
PlayerTeam.create!({ user_id: 2, driver1_id: 4, driver2_id: 6, engine_id: 2, chassis_manufacturer_id: 5 })
PlayerTeam.create!({ user_id: 3, driver1_id: 6, driver2_id: 8, engine_id: 3, chassis_manufacturer_id: 1 })

ScoringOverview.create!({position:1, driver_qual: 30, driver_race: 100, chassis_qual: 15, chassis_race: 45})
ScoringOverview.create!({position:2, driver_qual: 20, driver_race: 80, chassis_qual: 10, chassis_race: 35})
ScoringOverview.create!({position:3, driver_qual: 18, driver_race: 70, chassis_qual: 7, chassis_race: 30})
ScoringOverview.create!({position:4, driver_qual: 16, driver_race: 60, chassis_qual: 5, chassis_race: 26})
ScoringOverview.create!({position:5, driver_qual: 15, driver_race: 50, chassis_qual: 4, chassis_race: 24})
ScoringOverview.create!({position:6, driver_qual: 14, driver_race: 40, chassis_qual: 3, chassis_race: 22})
ScoringOverview.create!({position:7, driver_qual: 13, driver_race: 35, chassis_qual: 2, chassis_race: 20})
ScoringOverview.create!({position:8, driver_qual: 12, driver_race: 28, chassis_qual: 1, chassis_race: 18})
ScoringOverview.create!({position:9, driver_qual: 11, driver_race: 24, chassis_qual: 0, chassis_race: 16})
ScoringOverview.create!({position:10, driver_qual: 10, driver_race: 20, chassis_qual: 0, chassis_race: 14})
ScoringOverview.create!({position:11, driver_qual: 9, driver_race: 16, chassis_qual: 0, chassis_race: 12})
ScoringOverview.create!({position:12, driver_qual: 8, driver_race: 14, chassis_qual: 0, chassis_race: 10})
ScoringOverview.create!({position:13, driver_qual: 7, driver_race: 10, chassis_qual: 0, chassis_race: 8})
ScoringOverview.create!({position:14, driver_qual: 6, driver_race: 8, chassis_qual: 0, chassis_race: 6})
ScoringOverview.create!({position:15, driver_qual: 5, driver_race: 6, chassis_qual: 0, chassis_race: 5})
ScoringOverview.create!({position:16, driver_qual: 4, driver_race: 5, chassis_qual: 0, chassis_race: 4})
ScoringOverview.create!({position:17, driver_qual: 3, driver_race: 4, chassis_qual: 0, chassis_race: 3})
ScoringOverview.create!({position:18, driver_qual: 2, driver_race: 3, chassis_qual: 0, chassis_race: 2})
ScoringOverview.create!({position:19, driver_qual: 1, driver_race: 2, chassis_qual: 0, chassis_race: 1})
ScoringOverview.create!({position:20, driver_qual: 0, driver_race: 1, chassis_qual: 0, chassis_race: 0})
ScoringOverview.create!({position:21, driver_qual: 0, driver_race: 0, chassis_qual: 0, chassis_race: 0})
ScoringOverview.create!({position:22, driver_qual: 0, driver_race: 0, chassis_qual: 0, chassis_race: 0})
ScoringOverview.create!({position:23, driver_qual: 0, driver_race: 0, chassis_qual: 0, chassis_race: 0})
ScoringOverview.create!({position:24, driver_qual: 0, driver_race: 0, chassis_qual: 0, chassis_race: 0})

ValueOverview.create!({position:1, driver_race:9000000,chassis_race:3000000})
ValueOverview.create!({position:2, driver_race:8000000,chassis_race:2500000})
ValueOverview.create!({position:3, driver_race:7500000,chassis_race:2000000})
ValueOverview.create!({position:4, driver_race:7000000,chassis_race:1750000})
ValueOverview.create!({position:5, driver_race:6000000,chassis_race:1500000})
ValueOverview.create!({position:6, driver_race:5500000,chassis_race:1250000})
ValueOverview.create!({position:7, driver_race:5000000,chassis_race:1000000})
ValueOverview.create!({position:8, driver_race:4000000,chassis_race:750000})
ValueOverview.create!({position:9, driver_race:3000000,chassis_race:500000})
ValueOverview.create!({position:10, driver_race:2000000,chassis_race:250000})
ValueOverview.create!({position:11, driver_race:1000000,chassis_race:100000})
ValueOverview.create!({position:12, driver_race:500000,chassis_race:0})
ValueOverview.create!({position:13, driver_race:0,chassis_race:0})
ValueOverview.create!({position:14, driver_race:0,chassis_race:0})
ValueOverview.create!({position:15, driver_race:-500000,chassis_race:-100000})
ValueOverview.create!({position:16, driver_race:-1000000,chassis_race:-250000})
ValueOverview.create!({position:17, driver_race:-2000000,chassis_race:-500000})
ValueOverview.create!({position:18, driver_race:-2500000,chassis_race:-750000})
ValueOverview.create!({position:19, driver_race:-3000000,chassis_race:-1000000})
ValueOverview.create!({position:20, driver_race:-3500000,chassis_race:-1250000})
ValueOverview.create!({position:21, driver_race:-4000000,chassis_race:-1500000})
ValueOverview.create!({position:22, driver_race:-4500000,chassis_race:-1750000})
ValueOverview.create!({position:23, driver_race:-5000000,chassis_race:-2000000})
ValueOverview.create!({position:24, driver_race:-5500000,chassis_race:-2250000})


